// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWxpCw2t8Y8X4-d55fXheb06lo6oPUOw',
    appId: '1:282333012427:web:c43b046a314c079593964e',
    messagingSenderId: '282333012427',
    projectId: 'banshara-218a6',
    authDomain: 'banshara-218a6.firebaseapp.com',
    storageBucket: 'banshara-218a6.firebasestorage.app',
    measurementId: 'G-CBC9D02WDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqCDyYafNFh5oTCEoQxG8jAkJiv4-u-k',
    appId: '1:282333012427:android:a46b52f82637d97593964e',
    messagingSenderId: '282333012427',
    projectId: 'banshara-218a6',
    storageBucket: 'banshara-218a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA55yArg25KY3gaVgjg5QGPhmdsLyqdB94',
    appId: '1:282333012427:ios:6eed5eb662890de993964e',
    messagingSenderId: '282333012427',
    projectId: 'banshara-218a6',
    storageBucket: 'banshara-218a6.firebasestorage.app',
    iosBundleId: 'com.example.banshara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA55yArg25KY3gaVgjg5QGPhmdsLyqdB94',
    appId: '1:282333012427:ios:6eed5eb662890de993964e',
    messagingSenderId: '282333012427',
    projectId: 'banshara-218a6',
    storageBucket: 'banshara-218a6.firebasestorage.app',
    iosBundleId: 'com.example.banshara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWxpCw2t8Y8X4-d55fXheb06lo6oPUOw',
    appId: '1:282333012427:web:6f583dc7b5f7b84393964e',
    messagingSenderId: '282333012427',
    projectId: 'banshara-218a6',
    authDomain: 'banshara-218a6.firebaseapp.com',
    storageBucket: 'banshara-218a6.firebasestorage.app',
    measurementId: 'G-7ZT0V4FQL7',
  );
}
